// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs2UpIyw7c_rX1aKTh2uBASV05VX5WZbQ',
    appId: '1:305863093659:web:fd4d7e663cca10c597053e',
    messagingSenderId: '305863093659',
    projectId: 'datewater-1b728',
    authDomain: 'datewater-1b728.firebaseapp.com',
    storageBucket: 'datewater-1b728.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuNmeCPRrVa361R9VJefSuGIw2S_Rt90',
    appId: '1:305863093659:android:0ebdb124714972a997053e',
    messagingSenderId: '305863093659',
    projectId: 'datewater-1b728',
    storageBucket: 'datewater-1b728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyeXojceyBh2Kassc9WeXDIrBeox-flvo',
    appId: '1:305863093659:ios:4f52a84f0737467797053e',
    messagingSenderId: '305863093659',
    projectId: 'datewater-1b728',
    storageBucket: 'datewater-1b728.appspot.com',
    iosClientId: '305863093659-28r0ajeifv1abs331ra6miqdq2e42m5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyeXojceyBh2Kassc9WeXDIrBeox-flvo',
    appId: '1:305863093659:ios:ab92e452d4e1604297053e',
    messagingSenderId: '305863093659',
    projectId: 'datewater-1b728',
    storageBucket: 'datewater-1b728.appspot.com',
    iosClientId: '305863093659-ogmedball7nq4cimclegnjg45pbfclto.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterc.RunnerTests',
  );
}
